#!/usr/bin/env node
/**
 * Compiles this repo's GitHub issues into a local directory an agent can
 * read with ordinary file tools: one `index.md` to scan, one file per
 * issue to open.
 *
 * Why this exists: open work lives in GitHub issues (AGENTS.md, "Tracking
 * open work"), but a file on disk is what a coding agent reads cheaply at
 * the start of a session. This closes that gap without moving the source of
 * truth back into the repo - the cache is generated, gitignored, and always
 * a copy.
 *
 * Two front ends, one compiler, because the two callers have different
 * GitHub access:
 *   - `--fetch` shells out to `gh`, which the maintainer has locally.
 *   - stdin (or `--from-json`) takes an already-fetched JSON array, which
 *     is how an agent feeds it: a Claude Code Remote session has the GitHub
 *     MCP tools but no `gh` binary and no token.
 *
 * Plain `.mjs` rather than the `.ts` AGENTS.md defaults to: this has to run
 * before `npm install` has necessarily happened, and the TypeScript loader
 * hook (`build/register.mjs`) needs esbuild out of `node_modules`.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DEFAULT_OUT = '.claude/cache/issues';

function arg(name, fallback = null) {
  const i = process.argv.indexOf(name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

function readStdin() {
  try {
    return readFileSync(0, 'utf8');
  } catch {
    return '';
  }
}

function fetchWithGh() {
  const fields = 'number,title,state,labels,body,createdAt,updatedAt,url,assignees,comments';
  return execFileSync('gh', ['issue', 'list', '--state', 'all', '--limit', '500', '--json', fields], {
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  });
}

/** Tolerant of the two shapes the front ends produce: a bare array, or `{issues: [...]}`. */
function parseIssues(raw) {
  const parsed = JSON.parse(raw);
  const list = Array.isArray(parsed) ? parsed : (parsed?.issues ?? []);
  if (!Array.isArray(list)) throw new TypeError('expected a JSON array of issues');
  return list;
}

const labelsOf = (issue) =>
  (issue.labels ?? []).map((l) => (typeof l === 'string' ? l : (l?.name ?? ''))).filter(Boolean);

const stateOf = (issue) => String(issue.state ?? 'OPEN').toUpperCase();

function slug(title) {
  return String(title ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60) || 'issue';
}

function issueFile(issue) {
  const labels = labelsOf(issue);
  const head = [
    `# #${issue.number} ${issue.title ?? ''}`,
    '',
    `- state: ${stateOf(issue)}`,
    labels.length ? `- labels: ${labels.join(', ')}` : null,
    issue.url ? `- url: ${issue.url}` : null,
    issue.updatedAt || issue.updated_at ? `- updated: ${issue.updatedAt ?? issue.updated_at}` : null,
    '',
    '---',
    '',
  ].filter((l) => l !== null);
  return `${head.join('\n')}${issue.body ?? '_no description_'}\n`;
}

function main() {
  const out = arg('--out', DEFAULT_OUT);
  const fromJson = arg('--from-json');

  let raw;
  if (process.argv.includes('--fetch')) raw = fetchWithGh();
  else if (fromJson) raw = readFileSync(fromJson, 'utf8');
  else raw = readStdin();

  if (!raw.trim()) {
    console.error(
      'no input. Pipe issue JSON in, pass --from-json <path>, or use --fetch where `gh` is available.'
    );
    process.exit(1);
  }

  const issues = parseIssues(raw).slice().sort((a, b) => (b.number ?? 0) - (a.number ?? 0));

  // Rebuilt from scratch every run: a stale file for an issue that has
  // since been deleted or renumbered is worse than no cache at all.
  rmSync(out, { recursive: true, force: true });
  mkdirSync(out, { recursive: true });

  const open = issues.filter((i) => stateOf(i) === 'OPEN');
  const closed = issues.filter((i) => stateOf(i) !== 'OPEN');

  const line = (i) => {
    const labels = labelsOf(i);
    return `- [#${i.number}](${i.number}-${slug(i.title)}.md) ${i.title ?? ''}` +
      `${labels.length ? ` _(${labels.join(', ')})_` : ''}`;
  };

  const index = [
    '# Issue cache',
    '',
    `Generated by \`.claude/scripts/issues.mjs\`. A copy, never the source of`,
    'truth - re-run it rather than editing anything here, and make changes on',
    'GitHub itself.',
    '',
    `${open.length} open, ${closed.length} closed.`,
    '',
    '## Open',
    '',
    ...(open.length ? open.map(line) : ['_none_']),
    '',
    '## Closed',
    '',
    ...(closed.length ? closed.map(line) : ['_none_']),
    '',
  ].join('\n');

  writeFileSync(join(out, 'index.md'), index);
  for (const i of issues) writeFileSync(join(out, `${i.number}-${slug(i.title)}.md`), issueFile(i));

  console.log(`${issues.length} issues written to ${out} (${open.length} open)`);
}

main();
