/**
 * Tile geometry measured from the Blender render.
 *
 * GENERATED by tools/center-placement/import-shelf-svg.ts from shelf_geometry.svg.
 * Do not edit by hand - re-trace in Inkscape and re-run the importer.
 *
 * Values are normalised to the tile edge (0-1), x against the traced width and
 * y against the traced height, so they carry no aspect of their own. `tile`
 * records the shape they were traced at, because that is the one thing the
 * normalisation throws away and the one thing that has to keep agreeing with
 * BASE_TILE in packages/web/src/lib/pyramid.ts.
 *
 * Rects are [x, y, w, h].
 */

export type RectTuple = [number, number, number, number];

/**
 * The open book's exact outline. `d` is an SVG path in the canonical
 * absolute M/L/C/Z grammar `normalizePath` emits (see the importer), every
 * coordinate a tile-normalised (x/vbW, y/vbH) fraction - so it can be handed
 * straight to an SVG `<path d>` inside a `viewBox="0 0 1 1"`. `bbox` is the
 * same shape as every other measured rect, for a caller that only needs a
 * quick containment check.
 */
export interface CenterBook {
  d: string;
  bbox: RectTuple;
}

export interface MeasuredData {
  source: string;
  tile: { w: number; h: number; aspect: number };
  opening: RectTuple;
  searchBox: RectTuple | null;
  /** hit region for the "sort by my favorites" switch - null on a trace with none */
  mineToggle: RectTuple | null;
  /** hit region for the "sort by most favorited" switch - null on a trace with none */
  countToggle: RectTuple | null;
  /** hit region for the reorder control - null on a trace with none */
  shuffleButton: RectTuple | null;
  centerBook: CenterBook | null;
  /**
   * The "enable distillation" icon's outline, traced over the whole tile the
   * same way `centerBook` is - null on a trace with none, in which case the
   * distill toggle draws no hover highlight.
   */
  distillOff: CenterBook | null;
  /** The "disable distillation" icon's outline - see `distillOff`. */
  distillOn: CenterBook | null;
  /**
   * The on-tile favorite badge's non-transparent silhouette - an ellipse in
   * the trace, converted on import to the same M/L/C/Z grammar `centerBook`
   * uses. Traced over the WHOLE tile, not the badge's own icon, so it is in
   * the same per-axis fraction space as every other rect here; a consumer
   * scales it by a tile's `cellPx` exactly like `centerBook`. Null on a
   * trace with none, in which case a badge draws no hover highlight.
   */
  favoriteToggle: CenterBook | null;
  shelves: { books: RectTuple[] }[];
}

export const MEASURED: MeasuredData = {
  source: "shelf_geometry.svg",
  tile: { w: 1365.3333, h: 1024, aspect: 0.75 },
  opening: [0.2932, 0.34284, 0.41714, 0.52487],
  searchBox: [0.03797, 0.01902, 0.92541, 0.06957],
  mineToggle: [0.10618, 0.10876, 0.10559, 0.08384],
  countToggle: [0.10618, 0.20406, 0.10559, 0.08384],
  shuffleButton: [0.15364, 0.31915, 0.06288, 0.08068],
  centerBook: { d: "M0.42203,0.50503 L0.41485,0.64234 L0.41915,0.64569 L0.42513,0.64569 C0.42428,0.64843 0.42315,0.65109 0.42271,0.65401 C0.42163,0.65877 0.42248,0.66359 0.4224,0.66834 L0.42298,0.67547 L0.42471,0.67981 L0.57631,0.67981 L0.57726,0.66702 L0.57684,0.65408 L0.57362,0.64569 L0.5862,0.64457 C0.58605,0.63139 0.58452,0.61546 0.58332,0.60018 C0.58241,0.56886 0.58304,0.53766 0.58076,0.50615 L0.57068,0.50196 L0.55013,0.5014 L0.52463,0.50252 C0.5203,0.5029 0.51592,0.50369 0.51173,0.50531 C0.50835,0.50671 0.50465,0.50883 0.50072,0.51188 C0.50072,0.51188 0.49937,0.51028 0.49874,0.51 C0.49811,0.50972 0.49266,0.50643 0.49266,0.50643 L0.48193,0.50252 L0.47025,0.50112 L0.45445,0.5 L0.43778,0.5007 L0.4311,0.50217 Z", bbox: [0.41485, 0.5, 0.17135, 0.17981] },
  distillOff: { d: "M0.82486,0.75427 L0.81885,0.76178 L0.82025,0.76661 L0.80242,0.80775 L0.7998,0.8038 L0.74255,0.8038 L0.74344,0.88685 L0.7992,0.88685 L0.81136,0.87222 L0.81136,0.8212 L0.80526,0.81202 L0.82413,0.76924 L0.82486,0.76929 L0.83087,0.76178 L0.82486,0.75427 Z", bbox: [0.74255, 0.75427, 0.08831, 0.13258] },
  distillOn: { d: "M0.74255,0.8038 C0.74285,0.83148 0.74314,0.85917 0.74344,0.88685 L0.7992,0.88685 C0.80326,0.88197 0.80731,0.87709 0.81136,0.87222 L0.81136,0.84756 C0.82144,0.85404 0.83152,0.86053 0.8416,0.86702 C0.84099,0.8706 0.84279,0.87438 0.84537,0.87549 C0.84763,0.8766 0.85036,0.87579 0.85201,0.87343 C0.85327,0.87167 0.85382,0.86903 0.85333,0.86667 C0.85257,0.86258 0.84908,0.86016 0.84609,0.86116 C0.8454,0.86135 0.84473,0.86178 0.84413,0.86221 C0.83321,0.85532 0.82229,0.84843 0.81136,0.84154 L0.81136,0.8212 C0.80751,0.8154 0.80365,0.8096 0.7998,0.8038 Z", bbox: [0.74255, 0.8038, 0.11127, 0.08305] },
  favoriteToggle: { d: "M0.97337,0.20137 C0.97057,0.21675 0.96155,0.22743 0.95322,0.22522 C0.9449,0.22302 0.94042,0.20877 0.94322,0.19339 C0.94603,0.17801 0.95505,0.16733 0.96337,0.16954 C0.9717,0.17174 0.97617,0.18599 0.97337,0.20137 Z", bbox: [0.94042, 0.16733, 0.03575, 0.0601] },
  shelves: [
    {
      books: [
        [0.2932, 0.34284, 0.02349, 0.1415],
        [0.32104, 0.34284, 0.02349, 0.1415],
        [0.34723, 0.34284, 0.02349, 0.1415],
        [0.3737, 0.34284, 0.02349, 0.1415],
        [0.40006, 0.34284, 0.02349, 0.1415],
        [0.42591, 0.34284, 0.02349, 0.1415],
        [0.452, 0.34284, 0.02349, 0.1415],
        [0.47714, 0.34284, 0.02349, 0.1415],
        [0.5038, 0.34284, 0.02349, 0.1415],
        [0.52969, 0.34284, 0.02349, 0.1415],
        [0.55519, 0.34284, 0.02349, 0.1415],
        [0.58116, 0.34284, 0.02349, 0.1415],
        [0.60681, 0.34284, 0.02349, 0.1415],
        [0.63291, 0.34284, 0.02349, 0.1415],
        [0.65944, 0.34284, 0.02349, 0.1415],
        [0.68616, 0.34284, 0.02349, 0.1415],
      ],
    },
    {
      books: [
        [0.2956, 0.53118, 0.02181, 0.1443],
        [0.32123, 0.53118, 0.02181, 0.1443],
        [0.34762, 0.53118, 0.02181, 0.1443],
        [0.37384, 0.53118, 0.02181, 0.1443],
        [0.6091, 0.53118, 0.02181, 0.1443],
        [0.63377, 0.53118, 0.02181, 0.1443],
        [0.66052, 0.53118, 0.02181, 0.1443],
        [0.68632, 0.53118, 0.02181, 0.1443],
      ],
    },
    {
      books: [
        [0.29501, 0.72174, 0.02063, 0.14597],
        [0.32087, 0.72174, 0.02063, 0.14597],
        [0.34729, 0.72174, 0.02033, 0.14597],
        [0.37472, 0.72174, 0.01974, 0.14597],
        [0.40035, 0.72174, 0.02092, 0.14597],
        [0.42579, 0.72174, 0.02181, 0.14597],
        [0.4521, 0.72174, 0.02181, 0.14597],
        [0.47811, 0.72174, 0.02181, 0.14597],
        [0.50415, 0.72174, 0.02181, 0.14597],
        [0.53051, 0.72174, 0.02181, 0.14597],
        [0.55703, 0.72174, 0.02181, 0.14597],
        [0.58354, 0.72174, 0.02181, 0.14597],
        [0.61041, 0.72174, 0.02003, 0.14597],
        [0.63651, 0.72174, 0.02003, 0.14597],
        [0.66275, 0.72174, 0.02033, 0.14597],
        [0.68942, 0.72174, 0.02092, 0.14597],
      ],
    },
  ],
};

export const SHELF_COUNT = 3;
export const BOOK_COUNT = 40;
