/**
 * Tile geometry measured from the Blender render.
 *
 * GENERATED by tools/center-placement/import-shelf-svg.ts from shelf_geometry.svg.
 * Do not edit by hand - re-trace in Inkscape and re-run the importer.
 *
 * Values are normalised to the tile edge (0-1), x against the traced width and
 * y against the traced height, so they carry no aspect of their own. `tile`
 * records the shape they were traced at, because that is the one thing the
 * normalisation throws away and the one thing that has to keep agreeing with
 * BASE_TILE in packages/web/src/lib/pyramid.ts.
 *
 * Rects are [x, y, w, h].
 */

export type RectTuple = [number, number, number, number];

/**
 * The open book's exact outline. `d` is an SVG path in the canonical
 * absolute M/L/C/Z grammar `normalizePath` emits (see the importer), every
 * coordinate a tile-normalised (x/vbW, y/vbH) fraction - so it can be handed
 * straight to an SVG `<path d>` inside a `viewBox="0 0 1 1"`. `bbox` is the
 * same shape as every other measured rect, for a caller that only needs a
 * quick containment check.
 */
export interface CenterBook {
  d: string;
  bbox: RectTuple;
}

export interface MeasuredData {
  source: string;
  tile: { w: number; h: number; aspect: number };
  opening: RectTuple;
  searchBox: RectTuple | null;
  /** hit region for the "sort by my favorites" switch - null on a trace with none */
  mineToggle: RectTuple | null;
  /** hit region for the "sort by most favorited" switch - null on a trace with none */
  countToggle: RectTuple | null;
  /** hit region for the reorder control - null on a trace with none */
  shuffleButton: RectTuple | null;
  centerBook: CenterBook | null;
  /**
   * The on-tile favorite badge's non-transparent silhouette - an ellipse in
   * the trace, converted on import to the same M/L/C/Z grammar `centerBook`
   * uses. Traced over the WHOLE tile, not the badge's own icon, so it is in
   * the same per-axis fraction space as every other rect here; a consumer
   * scales it by a tile's `cellPx` exactly like `centerBook`. Null on a
   * trace with none, in which case a badge draws no hover highlight.
   */
  favoriteToggle: CenterBook | null;
  shelves: { books: RectTuple[] }[];
}

export const MEASURED: MeasuredData = {
  source: "shelf_geometry.svg",
  tile: { w: 1365.3333, h: 1024, aspect: 0.75 },
  opening: [0.29279, 0.34284, 0.41296, 0.52487],
  searchBox: [0.03797, 0.01902, 0.92541, 0.06957],
  mineToggle: [0.10618, 0.10876, 0.10559, 0.08384],
  countToggle: [0.10618, 0.20406, 0.10559, 0.08384],
  shuffleButton: [0.15364, 0.31915, 0.06288, 0.08068],
  centerBook: { d: "M0.42203,0.50503 L0.41485,0.64234 L0.41915,0.64569 L0.42513,0.64569 C0.42428,0.64843 0.42315,0.65109 0.42271,0.65401 C0.42163,0.65877 0.42248,0.66359 0.4224,0.66834 L0.42298,0.67547 L0.42471,0.67981 L0.57631,0.67981 L0.57726,0.66702 L0.57684,0.65408 L0.57362,0.64569 L0.5862,0.64457 C0.58605,0.63139 0.58452,0.61546 0.58332,0.60018 C0.58241,0.56886 0.58304,0.53766 0.58076,0.50615 L0.57068,0.50196 L0.55013,0.5014 L0.52463,0.50252 C0.5203,0.5029 0.51592,0.50369 0.51173,0.50531 C0.50835,0.50671 0.50465,0.50883 0.50072,0.51188 C0.50072,0.51188 0.49937,0.51028 0.49874,0.51 C0.49811,0.50972 0.49266,0.50643 0.49266,0.50643 L0.48193,0.50252 L0.47025,0.50112 L0.45445,0.5 L0.43778,0.5007 L0.4311,0.50217 Z", bbox: [0.41485, 0.5, 0.17135, 0.17981] },
  favoriteToggle: { d: "M0.97571,0.19397 C0.9729,0.20935 0.96388,0.22003 0.95556,0.21783 C0.94723,0.21562 0.94276,0.20137 0.94556,0.18599 C0.94836,0.17061 0.95739,0.15993 0.96571,0.16214 C0.97404,0.16434 0.97851,0.17859 0.97571,0.19397 Z", bbox: [0.94276, 0.15993, 0.03575, 0.0601] },
  shelves: [
    {
      books: [
        [0.2932, 0.34284, 0.02349, 0.1415],
        [0.31874, 0.34284, 0.02349, 0.1415],
        [0.3443, 0.34284, 0.02349, 0.1415],
        [0.36929, 0.34284, 0.02349, 0.1415],
        [0.39566, 0.34284, 0.02349, 0.1415],
        [0.42203, 0.34284, 0.02349, 0.1415],
        [0.4484, 0.34284, 0.02349, 0.1415],
        [0.47477, 0.34284, 0.02349, 0.1415],
        [0.50114, 0.34284, 0.02349, 0.1415],
        [0.52687, 0.34284, 0.02349, 0.1415],
        [0.55282, 0.34284, 0.02349, 0.1415],
        [0.57834, 0.34284, 0.02349, 0.1415],
        [0.60429, 0.34284, 0.02349, 0.1415],
        [0.63024, 0.34284, 0.02349, 0.1415],
        [0.65618, 0.34284, 0.02349, 0.1415],
        [0.68129, 0.34284, 0.02349, 0.1415],
      ],
    },
    {
      books: [
        [0.29279, 0.53118, 0.02181, 0.1443],
        [0.31915, 0.53118, 0.02181, 0.1443],
        [0.3451, 0.53118, 0.02181, 0.1443],
        [0.37147, 0.53118, 0.02181, 0.1443],
        [0.60584, 0.53118, 0.02181, 0.1443],
        [0.63095, 0.53118, 0.02181, 0.1443],
        [0.65711, 0.53118, 0.02181, 0.1443],
        [0.68306, 0.53118, 0.02181, 0.1443],
      ],
    },
    {
      books: [
        [0.29323, 0.72174, 0.02181, 0.14597],
        [0.31939, 0.72174, 0.02181, 0.14597],
        [0.34492, 0.72174, 0.02181, 0.14597],
        [0.37087, 0.72174, 0.02181, 0.14597],
        [0.39723, 0.72174, 0.02181, 0.14597],
        [0.42298, 0.72174, 0.02181, 0.14597],
        [0.44913, 0.72174, 0.02181, 0.14597],
        [0.47529, 0.72174, 0.02181, 0.14597],
        [0.50103, 0.72174, 0.02181, 0.14597],
        [0.5274, 0.72174, 0.02181, 0.14597],
        [0.55377, 0.72174, 0.02181, 0.14597],
        [0.58013, 0.72174, 0.02181, 0.14597],
        [0.60566, 0.72174, 0.02181, 0.14597],
        [0.63161, 0.72174, 0.02181, 0.14597],
        [0.65756, 0.72174, 0.02181, 0.14597],
        [0.68393, 0.72174, 0.02181, 0.14597],
      ],
    },
  ],
};

export const SHELF_COUNT = 3;
export const BOOK_COUNT = 40;
